FROM node:20-alpine

WORKDIR /app

# Install curl and bash for healthcheck and scripting
RUN apk add --no-cache curl bash

COPY package*.json ./
RUN npm install

COPY . .

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 8545

CMD ["docker-entrypoint.sh"]
